# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Build with Gradle
      run: ./gradlew shadowJar
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-jars
        path: |
          build/libs
          
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/JusticeBot.key
        chmod 600 ~/.ssh/JusticeBot.key
        cat >>~/.ssh/config <<END
        Host azure
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/JusticeBot.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
    - name: Stop the bot
      run: ssh azure "sudo pkill -f 'java -jar /JusticeBot/'"
      
    - name: Upload jar on Azure VM
      run: |
        ssh azure 'echo "/usr/lib/jvm/java-18-openjdk-arm64/bin/java -jar /JusticeBot/JusticeBot-1.0-all.jar \"${{ secrets.BOT_TOKEN }}\" \"${{ secrets.CSV_MULTI_QUIZ }}\ \"${{ secrets.CSV_LISTE_MOTS }}\" >> /JusticeBot/log.txt 2>> /JusticeBot/log.txt" > /JusticeBot/run.sh'
        ssh azure 'sudo chmod 700 /JusticeBot/run.sh'
        scp build/libs/JusticeBot-1.0-all.jar azure:/JusticeBot
        
    - name: Start the bot
      run: ssh azure 'cd /JusticeBot ; sudo ./run.sh > /dev/null' &

